### ISSUE TITLE
Offset Auto

### ISSUE THREAD

**Issue by validkeys** [corbanbrook/subdivision#1]
Here:

https://github.com/corbanbrook/subdivision/blob/master/packages/scss/src/mixins.scss#L10

You are required to specify a fractional offset. If I want my cell to be aligned all the way to the right, I could also specify:

```css
margin-left: auto;
```

So being able to provide either a number of the string "auto" could save time there. But just an enhancement, not a necessity. 

But maybe the gutter calc will fuck this up. So probably a no go. Here's a [JS Bin](http://jsbin.com/zeyiqet/edit?html,css,output)

**Comment by corbanbrook** [comment]
I have updated the offset function to accept unitless numbers, unit numbers, or strings like auto.

For unitless numbers it assumes it is getting a ratio and multiplies by 100% and does gutter calculations. For unit numbers like +/-24px it expects you want to offset it by exactly that much and does no such gutter calculations.
